name: Deploy SecureAuth-Lite

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd ~/apps/SecureAuth-Lite
          git pull origin main

      - name: Rebuild and restart container
        run: |
          cd ~/apps/SecureAuth-Lite
          docker-compose up --build -d

      - name: Verify API container is running
        run: |
          sleep 5
          docker ps | grep secureauth-lite-api
          
      - name: Verify frontend container is running
        run: |
          sleep 5
          docker ps | grep secureauth-lite-frontend